-- MySQL Script generated by MySQL Workbench
-- Thu Jun 12 17:40:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `restaurante` ;

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restaurante` ;

-- -----------------------------------------------------
-- Table `restaurante`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `reset_password_token` VARCHAR(255) NULL DEFAULT NULL,
  `reset_password_expires` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`roles` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`empleados` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `rol_id` INT NOT NULL,
  `salario` DECIMAL(10,0) NOT NULL,
  `status` ENUM('ACTIVO', 'INACTIVO') NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `usuario_id` INT NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `reset_password_token` VARCHAR(255) NULL DEFAULT NULL,
  `reset_password_expires` VARCHAR(255) NULL DEFAULT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `activo` ENUM('ACTIVO', 'INACTIVO') NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id`, `rol_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `fk_empleados_roles` (`rol_id` ASC) VISIBLE,
  INDEX `fk_usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_empleados_roles1_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `restaurante`.`usuarios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_empleados_roles1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `restaurante`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`ingredientes` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`ingredientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `alergeno` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`inventario` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ingrediente_id` INT NULL DEFAULT NULL,
  `cantidad` INT NOT NULL,
  `fecha_actualizacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ingrediente_id` (`ingrediente_id` ASC) VISIBLE,
  CONSTRAINT `inventario_ibfk_1`
    FOREIGN KEY (`ingrediente_id`)
    REFERENCES `restaurante`.`ingredientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`menus` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`menus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`platos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`platos` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`platos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`menus_platos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`menus_platos` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`menus_platos` (
  `menu_id` INT NOT NULL,
  `plato_id` INT NOT NULL,
  PRIMARY KEY (`menu_id`, `plato_id`),
  INDEX `menus_platos_ibfk_2` (`plato_id` ASC) VISIBLE,
  CONSTRAINT `menus_platos_ibfk_1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `restaurante`.`menus` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `menus_platos_ibfk_2`
    FOREIGN KEY (`plato_id`)
    REFERENCES `restaurante`.`platos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empleado_id` INT NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `aprobado` TINYINT(1) NULL DEFAULT '0',
  `aprobado_por` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `empleado_id` (`empleado_id` ASC) VISIBLE,
  INDEX `aprobado_por` (`aprobado_por` ASC) VISIBLE,
  CONSTRAINT `pedidos_ibfk_1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `restaurante`.`empleados` (`id`),
  CONSTRAINT `pedidos_ibfk_2`
    FOREIGN KEY (`aprobado_por`)
    REFERENCES `restaurante`.`empleados` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`pedidos_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`pedidos_detalle` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`pedidos_detalle` (
  `pedido_id` INT NOT NULL,
  `ingrediente_id` INT NOT NULL,
  `cantidad` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`pedido_id`, `ingrediente_id`),
  INDEX `ingrediente_id` (`ingrediente_id` ASC) VISIBLE,
  CONSTRAINT `pedidos_detalle_ibfk_1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `restaurante`.`pedidos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `pedidos_detalle_ibfk_2`
    FOREIGN KEY (`ingrediente_id`)
    REFERENCES `restaurante`.`ingredientes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`platos_ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`platos_ingredientes` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`platos_ingredientes` (
  `plato_id` INT NOT NULL,
  `ingrediente_id` INT NOT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  PRIMARY KEY (`plato_id`, `ingrediente_id`),
  INDEX `platos_ingredientes_ibfk_2` (`ingrediente_id` ASC) VISIBLE,
  CONSTRAINT `platos_ingredientes_ibfk_1`
    FOREIGN KEY (`plato_id`)
    REFERENCES `restaurante`.`platos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `platos_ingredientes_ibfk_2`
    FOREIGN KEY (`ingrediente_id`)
    REFERENCES `restaurante`.`ingredientes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`tareas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`tareas` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`tareas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NULL DEFAULT NULL,
  `empleado_id` INT NOT NULL,
  `fecha_finalizacion` DATE NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `estado` ENUM('Completada', 'En curso', 'Pendiente') NULL DEFAULT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_finalizacion` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tareas_ibfk_1` (`empleado_id` ASC) VISIBLE,
  CONSTRAINT `tareas_ibfk_1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `restaurante`.`empleados` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`turnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`turnos` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`turnos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empleado_id` INT NULL DEFAULT NULL,
  `fecha` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `turnos_ibfk_1` (`empleado_id` ASC) VISIBLE,
  CONSTRAINT `turnos_ibfk_1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `restaurante`.`empleados` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;