@host = http://localhost:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo1LCJpYXQiOjE3NDg5Mjg1MzMsImV4cCI6MTc0ODkzMjEzM30.Hwck22WkQgK7QegG4kMi5qz3eVkZGTE1xoWz7Bdj_Bc
###############
## EMPLEADOS ##
###############
### Pedir todos los empleados
GET {{host}}/api/empleados?page=1&limit=10

### Pedir todos los empleados con autorizacion de cabecera
GET {{host}}/api/empleados?page=1&limit=10
Authorization:{{token}} 

### crear un empleado

POST {{host}}/api/empleados
Content-Type: application/json

{
  "nombre": "Patricia Gomez",
  "pass": "000123",
  "email": "patricia@gmail.com",
  "telefono": "678965423",
  "rol_id":3,
  "usuario_id": 1
 
}

### Actualizar empleados por id

PUT {{host}}/api/empleados/1
Content-Type: application/json

{
  "nombre": "Manuel Perez",
  "pass": "123456",
  "email": "ManuelP23@gmail.com",
  "telefono": "658789456",
  "rol_id": 3  
}

### Pedir un empleado con id 8 con autorizacion de cabecera
GET {{host}}/api/empleados/4
Authorization:{{token}}

### Eliminar un empleado por id
DELETE {{host}}/api/empleados/2

############
## TAREAS ##
############

### Pedir todas las tareas
GET {{host}}/api/tareas

### Pedir todas las tareas de un empleado con id 1

GET {{host}}/api/empleados/1

### Pedir una tarea con id 1
GET {{host}}/api/tareas/1

### pedir todas las tareas de un empleado

GET {{host}}/api/empleados/tareas

### Pedir todas las tareas de un empleado con id 1
GET {{host}}/api/tareas/empleado/1

### crear una tarea
POST {{host}}/api/tareas
Content-Type: application/json

{
  "descripcion": "Limpiar suelo los martes",
  "empleado_id": 1,
  "menu_id": 3,
  "fecha":"2025-10-18"
}


### Actualizar tareas por id
PUT {{host}}/api/tareas/7
Content-Type: application/json
Authorization: {{token}}

{
  "descripcion": "Limpiar suelo los martes",
  "empleado_id": 1,
  "menu_id": 3,
  "fecha":"2025-10-18"
}

### Eliminar una tarea por id
DELETE {{host}}/api/tareas/2

######################################
## Fichero pdf con las tareas ##
######################################

### envio pdf con todas las tareas
GET {{host}}/api/tareas/export/pdf

### envio pdf con las tareas de un empleado
GET {{host}}/api/tareas/empleado/1/tareas/export/pdf


################################
## Envio email con las tareas ##
################################

### envio email con todas las tareas
POST {{host}}/api/tareas/send/pdf
Content-Type: application/json

{ "email": "waltra@gmail.com" }


### envio email con las tareas de un empleado
POST {{host}}/api/tareas/empleado/1/tareas/send/pdf
Content-Type: application/json

{ "email": "waltra@gmail.com" }

##############
## USUARIOS ##
##############


### Registrar usuarios
POST {{host}}/api/usuarios/registro
Content-Type: application/json

{
  "email": "dave4@gmail.com",
  "contraseña": "123456",
  "nombre": "David",
  "apellidos": "diaz"
}
### Login usuarios
POST {{host}}/api/usuarios/login
Content-Type: application/json

{
  "email": "waltra@gmail.com",
  "contraseña": "123456"
}

### Perfil de usuario por token
GET {{host}}/api/usuarios/perfil
Authorization: {{token}}


##################
## INGREDIENTES ##
##################

### Insertar ingredientes
POST {{host}}/api/ingredientes
Content-Type: application/json

{
  "nombre": "Leche",
  "alergeno":"Lactosa"
}

### Obtener ingredientes
GET {{host}}/api/ingredientes

### Obtener ingredientes por id
GET {{host}}/api/ingredientes/2

### Actualizar ingredientes
PUT {{host}}/api/ingredientes/1
Content-Type: application/json

{
  "nombre": "Harina",
  "alergeno":"polvo"

}

### Eliminar ingredientes
DELETE {{host}}/api/ingredientes/1

################
## INVENTARIO ##
################

### Insertar inventario
POST {{host}}/api/inventario
Content-Type: application/json

{
  "ingrediente_id": 2,
  "cantidad":5,
  "fecha_actualizacion": "2025-10-18"
}

### Obtener inventario
GET {{host}}/api/inventario

### Obtener inventario por id
GET {{host}}/api/inventario/1

### Actualizar inventario
PUT {{host}}/api/inventario/1
Content-Type: application/json

{
  "ingrediente_id": 3,
  "cantidad":510,
  "fecha_actualizacion": "2025-10-10"
}


### Eliminar inventario
DELETE {{host}}/api/inventario/1

###########
## MENUS ##
###########

### Insertar menus
POST {{host}}/api/menus
Content-Type: application/json

{
  "nombre": "Fabada",
  "descripcion":"Fabada asturiana riquisima"
  
}

### Obtener menus
GET {{host}}/api/menus

### Obtener menus por id
GET {{host}}/api/menus/1

### Actualizar menus
PUT {{host}}/api/menus/1
Content-Type: application/json

{
  "nombre": "Paella",
  "descripcion":"Paella de mariscos y carne"
  
}


### Eliminar menus
DELETE {{host}}/api/menus/2

#############
## PEDIDOS ##
#############

### Insertar pedidos
POST {{host}}/api/pedidos
Content-Type: application/json

{
  "empleado_id": 8,
  "fecha":"2025-05-18",
  "aprobado":1,
  "aprobado_por":1
  
}

### Obtener pedidos
GET {{host}}/api/pedidos

### Obtener pedidos por id
GET {{host}}/api/pedidos/1

### Actualizar pedidos
PUT {{host}}/api/pedidos/1
Content-Type: application/json

{
  "empleado_id":1,
  "fecha":"2025-05-28",
  "aprobado":0,
    
}


### Eliminar pedidos
DELETE {{host}}/api/pedidos/1

############
## PLATOS ##
############

### Insertar platos
POST {{host}}/api/platos
Content-Type: application/json

{
  "nombre": "filete de cerdo con patatas",
  "descripcion":"Riquisimo platoun filete de cerdo con patatas fritas"
    
}

### Obtener platos
GET {{host}}/api/platos

### Obtener platos por id
GET {{host}}/api/platos/1

### Actualizar platos
PUT {{host}}/api/platos/1
Content-Type: application/json

{
  "nombre": "huevo con salchicha",
  "descripcion":"Riquisimo plato de huevos con salchichas"
    
}


### Eliminar platos
DELETE {{host}}/api/platos/1

############
## ROLES ###
############

### Insertar roles
POST {{host}}/api/roles
Content-Type: application/json

{
  "nombre": "supervisor"    
}

### Obtener roles
GET {{host}}/api/roles

### Obtener roles por id
GET {{host}}/api/roles/1

### Actualizar roles
PUT {{host}}/api/roles/4
Content-Type: application/json

{
  "nombre": "jefe empleados"    
}


### Eliminar roles
DELETE {{host}}/api/roles/4

############
## TURNOS ##
############

### Insertar turnos
POST {{host}}/api/turnos
Content-Type: application/json

{
  "empleado_id": 1 ,
  "fecha":"2025-05-29",
  "hora_inicio":"10:00",
  "hora_fin":"18:00"    
}

### Obtener turnos
GET {{host}}/api/turnos

### Obtener turnos por id
GET {{host}}/api/turnos/2

### Actualizar turnos
PUT {{host}}/api/turnos/2
Content-Type: application/json

{
  "empleado_id": 1 ,
  "fecha":"2025-05-25",
  "hora_inicio":"11:00",
  "hora_fin":"19:00"    
}

### Eliminar turnos
DELETE {{host}}/api/turnos/4

##################
## MENUS_PLATOS ##
##################

### Insertar menus_platos
POST {{host}}/api/menusPlatos
Content-Type: application/json

{
  "menu_id": 2,
  "plato_id": 2  
}

### Obtener menusPlatos
GET {{host}}/api/menusPlatos


#########################
## PLATOS_INGREDIENTES ##
#########################

### Insertar platos_ingredientes
POST {{host}}/api/platosIngredientes
Content-Type: application/json

{
  "plato_id": 1,
  "ingrediente_id": 2,
  "cantidad": 3.5
}

### Obtener platos_ingredientes
GET {{host}}/api/platosIngredientes


#####################
## PEDIDOS_DETALLE ##
#####################

### Insertar pedidos_detalle
POST {{host}}/api/pedidosDetalle
Content-Type: application/json

{
  "pedido_id": 1,
  "ingrediente_id": 2,
  "cantidad": 3.5
}

### Obtener pedidos_detalle
GET {{host}}/api/pedidosDetalle

### Eliminar pedidos_detalle
DELETE {{host}}/api/pedidosDetalle/pedido/1

### recuperar contraseña
POST {{host}}/api/usuarios/recuperar-contrasena
Content-Type: application/json

{
  "email": "waltra@gmail.com"
}

### Cambiar contraseña
POST {{host}}/api/usuarios/restablecer-contrasena/
Content-Type: application/json

{
  "nuevaContrasena": "001234"
}

###
GET {{host}}/api/empleados/role

###
POST {{host}}/api/usuarios
Content-Type: application/json

{
  "nombre":"Manuel",
  "apellidos":"Perez",
  "email":"waltra@gmail.com"
}
